development:
  secret_key_base:  asdflkjasbfrgb57sf85bs6b8s4bs

test:
  secret_key_base:  asdflkhaslbs1f96g84bs6f84b6f

production:
  secret_key_base: 523lk5h2lkdfvtb1n96s816bs8164

local:
  secret_key_base: sdva1c6a5v1d81va68ta618dav16
