#!/usr/bin/env ruby

path = 'config/initializers/secret_key_base.rb'
secret = Random.new.bytes(40).unpack('H*')[0]

if File.exist? path
    puts "#{path}:file exists, if you want to regen, remove it first"
    exit
end

text = <<EOL
# Aumaticaly generated by #{$0} or make `gen-secret-key-base`
# Be sure to restart your server when you modify this file.

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.

Tep::Application.config.secret_key_base = '#{secret}'
EOL

File.write(path, text)
puts "Secret written into #{path}"
